name: Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: true
        default: "World"

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello ${{ github.event.inputs.name }}!"